### ISSUE TITLE
Custom tools for chaos mod

### ISSUE THREAD

**Issue by der-baumkrieger** [NLferdiNL/Teardown-Chaos-Mod#14]
Is there a way to implement tools to the chaos mod

**Comment by NLferdiNL** [comment]
It is theoretically possible yes. You should be able to register tools in start. And control them in ontick. But remember once the effect runs out so does any ability to control the tool. 

You can auto switch to that tool too by changing the current tool.

You wanna make sure you can take away the tool afterwards. Because it becomes useless at that point.

**Comment by der-baumkrieger** [comment]
Thanks for helping
