### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by der-baumkrieger** [NLferdiNL/Teardown-Chaos-Mod#9]
I want to make a map floating effect and I need some information about Bild in effects thank you:)

**Comment by NLferdiNL** [comment]
Could you elaborate? What do you want more information about?

About putting your own effects into the effects.lua file?

**Comment by der-baumkrieger** [comment]
How can I change the pos of something with Luca

**Comment by der-baumkrieger** [comment]
*lua

**Comment by NLferdiNL** [comment]
I'll write a full response when I get home,

For now here you can find a few tutorials from the Teardown devs: https://www.teardowngame.com/modding/

And here is the API documentation:
https://teardowngame.com/modding/api.html

In the API docs you can find all functions Teardown currently has available.

**Comment by der-baumkrieger** [comment]
Is it possible to change the pos of water

**Comment by der-baumkrieger** [comment]
I don't think so

**Comment by NLferdiNL** [comment]
No, you cannot change the position of water. (Atleast officially, maybe with third party modifications to the game, but that is out of the scope of this mod.)

The theory below might not be possible. I haven't had the time to test it.

If you want to make a flood effect you could see if it's possible to draw a sprite flat, use depth test to make it render behind things and then fake water physics on objects nearby you and the player. You can do that using ApplyBodyImpulse, that takes body mass into account so heavy things will sink rather than float.

You can use an QueryAabbShapes to get all shapes that should be affected by water by only looking below water.

**Comment by NLferdiNL** [comment]
Closing this issue because it seems to be resolved.
